# Format: <plugin_name>|<git_repo_url>
zsh-autosuggestions|https://github.com/zsh-users/zsh-autosuggestions
zsh-syntax-highlighting|https://github.com/zsh-users/zsh-syntax-highlighting.git
zsh-fzf-history-search|https://github.com/joshskidmore/zsh-fzf-history-search.git
forgit|https://github.com/wfxr/forgit.git
